default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myunsplash_development
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: myunsplash_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: myunsplash_production
